"""
Local LLM reasoning module.

The pipeline stays fully offline by calling a local Ollama model.
Priority is hardcoded per sound class (deterministic, instant); the
human-facing message is generated by the LLM.

Optimisations applied:
  - num_ctx=256       — KV cache size matched to our ~50-token interaction
                        (default 8192 wastes RAM and slows inference).
  - num_thread=2      — caps CPU usage so SED/DOA aren't starved.
  - num_predict=48    — output cap (~80 chars worth of tokens).
  - bucketed cache    — same class + direction-bucket + distance-bucket
                        returns a cached message instantly.

To swap to direct llama-cpp-python later: replace the Ollama call inside
``_run_llm`` — the rest (priorities, cache, fallback) stays identical.
"""
from __future__ import annotations

import subprocess
import time
import urllib.request
import urllib.error
from collections import OrderedDict
from typing import get_args

from contracts.types import LLMInput, LLMOutput, Priority, SoundClass


# ── Priority table — covers all 10 macros (matches docs/infernceclass.md) ──
_PRIORITIES: dict[SoundClass, Priority] = {
    "crying":       "high",     # safety-critical (infant + adult)
    "alarm":        "high",     # alarms + emergency sirens
    "broken_glass": "high",     # security risk
    "scream":       "high",     # distress / safety signal
    "dog":          "medium",   # context-dependent (bark vs growl)
    "metal_sound":  "medium",   # context-dependent
    "doorbell":     "low",      # informational
    "knock":        "low",      # informational, presence at door
    "phone":        "low",      # informational
    "clap":         "low",      # may be noise
}
# Fail-loud: catch any future macro added to SoundClass without a priority.
assert set(_PRIORITIES.keys()) == set(get_args(SoundClass)), (
    "Missing priority entries for: "
    f"{set(get_args(SoundClass)) - set(_PRIORITIES.keys())}"
)

_FALLBACK_PRIORITY: Priority = "medium"
_FALLBACK_MESSAGE = "Sound detected — could not assess urgency"

_SYSTEM_PROMPT = (
    "/no_think"
    "You are a sound alert system for hearing-impaired users. "
    "You receive a detected sound label and respond with exactly one short, direct sentence describing what is happening nearby."
    "Rules: under 15 words, no explanations, never say 'I', no punctuation other than a period, be literal and factual, no dramatization or emotional language."
)

# Ollama options — tuned for fast CPU inference of small interactions.
_OLLAMA_OPTIONS = {
    "num_ctx": 256,         # context window — way smaller than the 8192 default
    "num_thread": 2,        # leave CPU room for SED + DOA
    "num_predict": 48,      # output token cap (~80 chars)
    "temperature": 0.7,
}

# ── Cache ──────────────────────────────────────────────────────────────────
# Keys are (sound_class, direction_bucket, distance_bucket); bucketing avoids
# treating two events with near-identical geometry as different.
_CACHE_MAX = 256


def _direction_bucket(deg: float) -> int:
    """12 buckets over -90° to 90° range (180° total), one every 15°."""
    normalized = deg + 90  # -90 -> 0, 90 -> 180
    return int(normalized // 15)


def _distance_bucket(m: float) -> str:
    """3 coarse buckets — fine enough for a one-line description."""
    if m <= 1.0:
        return "near"
    if m <= 3.0:
        return "mid"
    return "far"


class LLMReasoner:
    """Local Ollama-backed reasoner for alert generation."""

    _OLLAMA_URL = "http://localhost:11434"
    _START_TIMEOUT = 15  # seconds to wait for Ollama to become ready

    def __init__(self) -> None:
        self._model = "gemma3:1b"
        self._cache: OrderedDict[tuple[str, int, str], str] = OrderedDict()
        self._ensure_ollama_running()

    # ----------------------------------------------------------- server mgmt
    def _is_ollama_ready(self) -> bool:
        try:
            urllib.request.urlopen(self._OLLAMA_URL, timeout=1)
            return True
        except Exception:
            return False

    def _ensure_ollama_running(self) -> None:
        if self._is_ollama_ready():
            return
        try:
            subprocess.Popen(
                ["ollama", "serve"],
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
            )
        except FileNotFoundError:
            return  # ollama not installed; fallback message will be used
        deadline = time.monotonic() + self._START_TIMEOUT
        while time.monotonic() < deadline:
            time.sleep(0.5)
            if self._is_ollama_ready():
                return

    # ------------------------------------------------------------------ public
    def reason(self, input: LLMInput) -> LLMOutput:  # noqa: A002
        """
        Return (priority, message). Priority is deterministic from class;
        message is cached or generated by the LLM with a 1 s budget.

        On any error (Ollama unreachable, malformed output) returns the
        fallback so the pipeline never stalls.
        """
        priority = _PRIORITIES.get(input.sound_class, _FALLBACK_PRIORITY)

        cache_key = (
            input.sound_class,
            _direction_bucket(input.doa_direction_of_arrival),
            _distance_bucket(input.doa_distance_estimation),
        )

        cached = self._cache.get(cache_key)
        if cached is not None:
            self._cache.move_to_end(cache_key)
            return LLMOutput(priority=priority, message=cached)

        message = self._run_llm(input)
        if message is None:
            return LLMOutput(priority=priority, message=_FALLBACK_MESSAGE)

        self._cache[cache_key] = message
        if len(self._cache) > _CACHE_MAX:
            self._cache.popitem(last=False)
        return LLMOutput(priority=priority, message=message)

    # ----------------------------------------------------------------- private
    def _run_llm(self, input: LLMInput) -> str | None:  # noqa: A002
        try:
            import ollama

            user_prompt = (
                f"sound: {input.sound_class}; "
                f"direction: {input.doa_direction_of_arrival:.0f}°; "
                f"distance: {input.doa_distance_estimation:.1f} m"
            )
            response = ollama.chat(
                model=self._model,
                messages=[
                    {"role": "system", "content": _SYSTEM_PROMPT},
                    {"role": "user", "content": user_prompt},
                ],
                options=_OLLAMA_OPTIONS,
            )
            content = response.message.content or ""
            message = content.strip()
            return message[:80] if message else None
        except Exception:
            return None
