"""
Local LLM reasoning module.

The pipeline stays fully offline by calling a local Ollama model.
Priority is hardcoded per sound class (deterministic, instant); the
human-facing message is generated by the LLM.

Optimisations applied:
  - num_ctx=256       — KV cache size matched to our ~50-token interaction
                        (default 8192 wastes RAM and slows inference).
  - num_thread=2      — caps CPU usage so SED/DOA aren't starved.
  - num_predict=48    — output cap (~80 chars worth of tokens).
  - bucketed cache    — same class + direction-bucket + distance-bucket
                        returns a cached message instantly.

To swap to direct llama-cpp-python later: replace the Ollama call inside
``_run_llm`` — the rest (priorities, cache, fallback) stays identical.
"""
from __future__ import annotations

from collections import OrderedDict
from typing import get_args

from contracts.types import LLMInput, LLMOutput, Priority, SoundClass


# ── Priority table — covers all 10 macros (matches docs/infernceclass.md) ──
_PRIORITIES: dict[SoundClass, Priority] = {
    "crying":       "high",     # safety-critical (infant + adult)
    "alarm":        "high",     # alarms + emergency sirens
    "broken_glass": "high",     # security risk
    "scream":       "high",     # distress / safety signal
    "dog":          "medium",   # context-dependent (bark vs growl)
    "metal_sound":  "medium",   # context-dependent
    "doorbell":     "low",      # informational
    "knock":        "low",      # informational, presence at door
    "phone":        "low",      # informational
    "clap":         "low",      # may be noise
}
# Fail-loud: catch any future macro added to SoundClass without a priority.
assert set(_PRIORITIES.keys()) == set(get_args(SoundClass)), (
    "Missing priority entries for: "
    f"{set(get_args(SoundClass)) - set(_PRIORITIES.keys())}"
)

_FALLBACK_PRIORITY: Priority = "medium"
_FALLBACK_MESSAGE = "Sound detected — could not assess urgency"

_SYSTEM_PROMPT = (
    "You write one short alert for a hearing-impaired user. "
    "Describe what is happening around them in one direct sentence, "
    "under 80 characters. Never say 'I'. No explanations."
)

# Ollama options — tuned for fast CPU inference of small interactions.
_OLLAMA_OPTIONS = {
    "num_ctx": 256,         # context window — way smaller than the 8192 default
    "num_thread": 2,        # leave CPU room for SED + DOA
    "num_predict": 48,      # output token cap (~80 chars)
    "temperature": 0.7,
}

# ── Cache ──────────────────────────────────────────────────────────────────
# Keys are (sound_class, direction_bucket, distance_bucket); bucketing avoids
# treating two events with near-identical geometry as different.
_CACHE_MAX = 256


def _direction_bucket(deg: float) -> int:
    """12 buckets, one every 30°."""
    return int((deg % 360) // 30)


def _distance_bucket(m: float) -> str:
    """3 coarse buckets — fine enough for a one-line description."""
    if m <= 1.0:
        return "near"
    if m <= 3.0:
        return "mid"
    return "far"


class LLMReasoner:
    """Local Ollama-backed reasoner for alert generation."""

<<<<<<< HEAD
    def __init__(self) -> None:
        self._model = "gemma3:1b"
        # 1. Initialize our memory cache
        self._cache: dict[str, str] = {}
=======
    def __init__(self, model: str = "gemma3:1b") -> None:
        self._model = model
        self._cache: OrderedDict[tuple[str, int, str], str] = OrderedDict()
>>>>>>> cef4208 (optimize)

    # ------------------------------------------------------------------ public
    def reason(self, input: LLMInput) -> LLMOutput:  # noqa: A002
        """
        Return (priority, message). Priority is deterministic from class;
        message is cached or generated by the LLM with a 1 s budget.

<<<<<<< HEAD
        Constraints:
        - Must complete within 1000 ms on CPU.
        - message must be at most 80 characters.
        - priority must be one of "low" | "medium" | "high".
        - If the model returns malformed output, catch the error and return fallback.
        - NO network calls. Fully local/offline.
        """
        priority = _PRIORITIES.get(input.sound_class, _FALLBACK_PRIORITY)

        # ---------------------------------------------------------
        # SMART CACHING LOGIC
        # ---------------------------------------------------------
        # Bucket the numbers so similar events trigger the cache!
        # Example: 42.1° becomes 45.0°, 3.2m becomes 3m. 
        # We IGNORE confidence in the cache key so it doesn't break the cache.
        dir_bucket = round(input.doa_direction_of_arrival / 45.0) * 45.0
        dist_bucket = round(input.doa_distance_estimation)
        
        cache_key = f"{input.sound_class}_{dir_bucket}_{dist_bucket}"

        if cache_key in self._cache:
            # INSTANT RETURN (0ms latency!)
            print(f"⚡[LLM Cache Hit]: {cache_key}")
            return LLMOutput(priority=priority, message=self._cache[cache_key])
        # ---------------------------------------------------------

        try:
            import ollama
            
            print(f"[LLM Cache Miss]: Generating new message for {cache_key}...")
            
=======
        On any error (Ollama unreachable, malformed output) returns the
        fallback so the pipeline never stalls.
        """
        priority = _PRIORITIES.get(input.sound_class, _FALLBACK_PRIORITY)

        cache_key = (
            input.sound_class,
            _direction_bucket(input.doa_direction_of_arrival),
            _distance_bucket(input.doa_distance_estimation),
        )

        cached = self._cache.get(cache_key)
        if cached is not None:
            self._cache.move_to_end(cache_key)
            return LLMOutput(priority=priority, message=cached)

        message = self._run_llm(input)
        if message is None:
            # LLM unreachable: keep class-based priority, use generic message.
            return LLMOutput(priority=priority, message=_FALLBACK_MESSAGE)

        self._cache[cache_key] = message
        if len(self._cache) > _CACHE_MAX:
            self._cache.popitem(last=False)
        return LLMOutput(priority=priority, message=message)

    # ----------------------------------------------------------------- private
    def _run_llm(self, input: LLMInput) -> str | None:  # noqa: A002
        try:
            import ollama

            user_prompt = (
                f"sound: {input.sound_class}; "
                f"direction: {input.doa_direction_of_arrival:.0f}°; "
                f"distance: {input.doa_distance_estimation:.1f} m"
            )
>>>>>>> cef4208 (optimize)
            response = ollama.chat(
                model=self._model,
                messages=[
                    {"role": "system", "content": _SYSTEM_PROMPT},
                    {"role": "user", "content": user_prompt},
                ],
<<<<<<< HEAD
                # 2. Limit CPU Threads to save resources for Audio/SED!
                options={
                    "num_thread": 2, 
                    "num_predict": 30 # Stop it from rambling endlessly
                }
            )
            message = response.message.content.strip()
            if not message:
                raise ValueError("empty LLM response")
            
            # Save the clean message to our cache before returning
            final_message = message[:80]
            self._cache[cache_key] = final_message

        except Exception as e:
            print(f"LLM Error: {e}")
            return LLMOutput(priority=_FALLBACK_PRIORITY, message=_FALLBACK_MESSAGE)

        return LLMOutput(priority=priority, message=final_message)
=======
                options=_OLLAMA_OPTIONS,
            )
            content = response.message.content or ""
            message = content.strip()
            return message[:80] if message else None
        except Exception:
            return None
>>>>>>> cef4208 (optimize)
